name: Build Android arm64-v8a Release APK

on:
  workflow_dispatch:

env:
  DEPOT_TOOLS_UPDATE: 0
  DEPOT_TOOLS_REPORT_BUILD: 0
  DEPOT_TOOLS_COLLECT_METRICS: 0
  DEPOT_TOOLS_METRICS: 0
  IS_CI: 1

jobs:
  build:
    runs-on: [self-hosted, chrobalt-linux-runner]
    container:
      image: ghcr.io/${{ github.repository }}/linux:latest
      options: --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor=unconfined
      volumes:
        - /runner-cache:/runner-cache

    steps:
      - name: Restore CI Essentials
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: |
            .github
            cobalt/build
            cobalt/docker
            cobalt/tools

      - name: Prepare OverlayFS Workspace
        uses: ./.github/actions/overlay_workspace
        with:
          path: cobalt
          use_gcloud: true

      - name: Checkout
        uses: ./.github/actions/checkout
        with:
          path: cobalt/src
          ref: ${{ github.sha }}
          fetch_depth: 1
          use_cache: true

      - name: Set Up Depot Tools
        uses: ./.github/actions/depot_tools
        with:
          use_gcloud: true

      - name: GN Gen
        shell: bash
        run: |
          cd cobalt/src
          cobalt/build/gn.py -p android-arm64 -C gold

      - name: Build APK
        shell: bash
        run: |
          cd cobalt/src
          time autoninja -C out/android-arm64_gold cobalt:gn_all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-release-apk
          path: |
            cobalt/src/out/android-arm64_gold/apks/*.apk
            cobalt/src/out/android-arm64_gold/*_apk/*.apk
